flask_app/main/routes.py
from flask import render_template, request, current_app, Blueprint, redirect, url_for

import json
from flask_app.models import Post, User

main = Blueprint("main", __name__)


@main.route("/")
def index():
    posts = Post.query.all()[::-1]
    return render_template("index.html", title="GlitchHub Snippets", posts=posts)


@main.route("/about")
def about():
    return render_template("about.html", title="About")


@main.route("/user/<id>")
def user_detail(id):
    user = User.query.filter_by(id=id).first()

    return render_template(
        "user_detail.html",
        user=user,
        posts=user.posts[::-1],
        comments=user.comments[::-1],
    )


@main.route("/csp_error_handling", methods=["POST"])
def report_handler():
    """
    Receives POST requests from the browser whenever the Content-Security-Policy 
    is violated. Processes the data and logs an easy-to-read version of the message
    in your console.
    """
    report = json.loads(request.data.decode())["csp-report"]

    # current_app.logger.info(json.dumps(report, indent=2))

    violation_desc = "\nViolated directive: %s, \nBlocked: %s, \nOriginal policy: %s \n" % (
        report["violated-directive"],
        report["blocked-uri"],
        report["original-policy"]
    )

    current_app.logger.info(violation_desc)
    return redirect(url_for("main.index"))

flask_app/posts/routes.py
from flask import (
    render_template,
    url_for,
    redirect,
    request,
    Blueprint,
    session,
    current_app,
)
from flask_login import login_user, current_user, logout_user, login_required

from flask_app import db, bcrypt
from flask_app.models import User, Post, Comment
from flask_app.posts.forms import CreatePostForm, CommentForm


posts = Blueprint("posts", __name__)


@posts.route("/create_post_detail", methods=["GET", "POST"])
@login_required
def create_post_detail():
    form = CreatePostForm()

    if form.validate_on_submit():

        content = form.text.data

        post = Post(
            title=form.title.data,
            content=content,
            author=current_user,
        )

        db.session.add(post)
        db.session.commit()

        return redirect(url_for("posts.post_detail", id=post.id))

    return render_template(
        "create_post.html", title="New Code Snippet", form=form
    )


@posts.route("/posts/<id>", methods=["GET", "POST"])
def post_detail(id):
    post = Post.query.filter_by(id=id).first()
    comments = post.comments[::-1]

    return render_template("post_detail.html", post=post, comments=comments)


@posts.route("/posts/<id>/new_comment", methods=["GET", "POST"])
@login_required
def create_comment(id):
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(content=form.text.data,
                          author=current_user, post_id=id)

        db.session.add(comment)
        db.session.commit()

        return redirect(url_for("posts.post_detail", id=id))
    return render_template("create_comment.html", form=form)


@posts.route("/posts/<id>/edit", methods=["GET", "POST"])
@login_required
def edit_post(id):
    post = Post.query.filter_by(id=id).first()

    form = CreatePostForm()

    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.text.data
        db.session.commit()

        return redirect(url_for("posts.post_detail", id=id))
    else:
        form.title.data = post.title
        form.text.data = post.content

    return render_template(
        "edit_post.html", title="Edit Code Snippet", form=form
    )

flask_app/users/routes.py
from flask import render_template, url_for, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required

from flask_app import db, bcrypt
from flask_app.models import User, Post
from flask_app.users.forms import RegistrationForm, LoginForm
import pyotp

users = Blueprint("users", __name__)


@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = RegistrationForm()
    if request.method == 'POST' and form.validate():
        password = bcrypt.generate_password_hash(form.password.data)
        mfa_secret = pyotp.random_base32()
        new_user = User(username=form.username.data, email=form.email.data,
                        password=password, mfa_secret=mfa_secret)
        db.session.add(new_user)
        db.session.commit()
        qrcode = pyotp.totp.TOTP(mfa_secret).provisioning_uri(
            form.email.data, issuer_name="GlitchHub")
        return render_template('mfa_confirm_page.html', qrcode=qrcode)
    return render_template('register.html', form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
        
    # print(current_user)
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()

        if user is not None and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            return redirect(url_for("main.index"))
    return render_template('login.html', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.index"))

flask_app/templates/about.html
{% extends "base.html" %}
{% block content %}
{% filter markdown %}
# CMSC 388J FINAL PROJECT

This project is a Github Gist like project.

### Where

Deployed on PythonAnywhere [https://dickyt.pythonanywhere.com/](https://dickyt.pythonanywhere.com/about)

### Group Members

- Diqi Zeng

### Requirements

#### Login

- Login system implemented
- Reason: User need an account to create code snippets, also need an account to view and create comments.

[Registration (log out first pls)]({{ url_for('users.register') }})

[Login (log out first pls)]({{ url_for('users.login') }})

#### Forms

- At least 4 forms, 2 for user mgmt

- [User Register Form]({{ url_for('users.register') }})
- [User Login Form]({{ url_for('users.login') }})
- [Create Snippet Form]({{ url_for('posts.create_post_detail') }})
- Comment Create Form (under code snippet page)

#### Security

- Proper CSP -> Yes, by tailman
- CSRF protected -> Yes, by WTForm
- Tailsman -> Yes
- Passwords are hashed -> Yes
- 2FA -> 2FA is needed everytime login (for grading purpose, 114514 is the special MFA code to override this feature)

#### Blueprints

- At least 2 Blueprints
- At least 3 visible pages for each
- About page -> This page

##### Users Blueprint

- [User Register]({{ url_for('users.register') }})
- [User Login]({{ url_for('users.login') }})
- User Page - When you click username in code snippet detail

##### Posts Blueprint

- [Create Snippet]({{ url_for('posts.create_post_detail') }})
- Comment Create (under code snippet page)
- Posts update page (under code snippet page)

#### Looks nice

Doesn't this looks nice? lol

#### New Python Package

```
pyotp
Flask-Markdown
```

### Changes

Yes, I added a `edit` page for every post.

{% endfilter %}
<textarea style="display:none">
# CMSC 388J FINAL PROJECT

This project is a Github Gist like project.

### Source Code

### Where

Deployed on AWS [HE](http://github.com)

### Group Members

- Diqi Zeng

### Requirements

#### Login

- Login system implemented
- Reason: User need an account to create code snippets, also need an account to view and create comments.

[Registration (log out first pls)]({{ url_for('users.register') }})

[Login (log out first pls)]({{ url_for('users.login') }})

#### Forms

- At least 4 forms, 2 for user mgmt

- [User Register Form]({{ url_for('users.register') }})
- [User Login Form]({{ url_for('users.login') }})
- [Create Snippet Form]({{ url_for('posts.create_post_detail') }})
- Comment Create Form (under code snippet page)

#### Security

- Proper CSP -> Yes, by tailman
- CSRF protected -> Yes, by WTForm
- Tailsman -> Yes
- Passwords are hashed -> Yes
- 2FA -> 2FA is needed everytime login (for grading purpose, 114514 is the special MFA code to override this feature)

#### Blueprints

- At least 2 Blueprints
- At least 3 visible pages for each
- About page -> This page

##### Users Blueprint

- [User Register]({{ url_for('users.register') }})
- [User Login]({{ url_for('users.login') }})
- User Page - When you click username in code snippet detail

##### Posts Blueprint

- [Create Snippet]({{ url_for('posts.create_post_detail') }})
- Comment Create (under code snippet page)
- Posts update page (under code snippet page)

#### Looks nice

Doesn't this looks nice? lol

#### New Python Package

```
pyotp
Flask-Markdown
```

### Changes

Yes, I added a `edit` page for every post.
</textarea>
{% endblock %}

flask_app/templates/base.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>GlitchHub Snippets</title>
    {% endif %}
</head>

<body>
    <header>
        <div
            class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
            <h5 class="my-0 mr-md-auto font-weight-normal">GlitchHub Snippets</h5>
            <nav class="my-2 my-md-0 mr-md-3">
                <a class="p-2 text-dark" href="{{ url_for('main.index') }}">Home</a>
                <a class="p-2 text-dark" href="{{ url_for('main.about') }}">About</a>
                {% if current_user.is_authenticated %}
                <a class="p-2 text-dark" href="{{ url_for('main.user_detail', id=current_user.id) }}">
                    My Profile <b>[{{ current_user.username }}]</b></a>
                <a class="p-2 text-dark" href="{{ url_for('users.logout') }}">Logout</a>
                {% endif %}
            </nav>
            {% if current_user.is_authenticated %}
            <a class="btn btn-outline-primary" href="{{ url_for('posts.create_post_detail' )}}">New Snippet</a>
            {% else %}
            <a class="btn btn-outline-primary" href="{{ url_for('users.register' )}}" style="margin-right: 15px">Sign
                up</a>
            <a class="btn btn-outline-primary" href="{{ url_for('users.login' )}}">Sign In</a>
            {% endif %}
        </div>
    </header>

    <main class="container">
        <div class="row">
            <div class="col-md-12">
                {% block content %}{% endblock %}
            </div>
        </div>
    </main>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

flask_app/templates/create_comment.html
{% extends "base.html" %}
{% block content %}
<div>
    <h1>Create new comment <small>(Markdown Supported)</small></h1>
</div>
<div>
    <form action="" method="post">
        {{ form.csrf_token }}
        <div>
            {{ form.text(class="form-control form-control-lg", style="min-height: 600px") }}
        </div>
        <br>
        <div>
            {{ form.submit(class="btn btn-block btn-primary") }}
        </div>
    </form>
</div>
{% endblock %}

flask_app/templates/create_post.html
{% extends "base.html" %}
{% block content %}
<div>
    <h2>New Code Snippet</h2>
</div>
<div>
    <form action="" method="post">
        {{ form.csrf_token }}
        <div>
            {{ form.title.label(class="form-control-label") }}
            {{ form.title(class="form-control form-control-md") }}

            {% if form.title.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in form.title.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}

            <div>
                {{ form.text.label(class="form-control-label") }}
                {{ form.text(class="form-control form-control-lg", style="min-height: 550px;") }}
            </div>
            <br>
            <div>
                {{ form.submit(class="btn btn-block btn-primary") }}
            </div>
        </div>
    </form>
</div>
{% endblock %}

flask_app/templates/edit_post.html
{% extends "base.html" %}
{% block content %}
<div>
    <h2>Edit Code Snippet</h2>
</div>
<div>
    <form action="" method="post">
        {{ form.csrf_token }}
        <div>
            {{ form.title.label(class="form-control-label") }}
            {{ form.title(class="form-control form-control-md") }}

            {% if form.title.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in form.title.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}

            <div>
                {{ form.text.label(class="form-control-label") }}
                {{ form.text(class="form-control form-control-lg", style="min-height: 550px;") }}
            </div>
            <br>
            <button class="btn btn-block btn-primary">Update Snippet</button>
        </div>
    </form>
</div>
{% endblock %}

flask_app/templates/index.html
{% extends "base.html" %}
{% block content %}
<div>
    <h1>GlitchHub Snippets</h1>
    <br>
</div>

<div class="list-group">
    {% for post in posts %}
    <div class="card mb-4 shadow-sm" style="cursor: pointer;" data-href="{{ url_for('posts.post_detail', id=post.id) }}"
        onclick="location.href=this.getAttribute('data-href');">
        <div class="card-body">
            <p class="card-text">{{ post.title }}</p>
            <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">
                    {{ post.author.username }}
                </small>
                <small class="text-muted">
                    {{ post.date.strftime('%b %d, %Y at %I:%M %p') }}
                </small>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

flask_app/templates/login.html
{% extends "base.html" %}
{% block content %}
<div>
    <h2>Log In</h2>
</div>
<div>
    If you <b>don't</b> have an account, then <a href={{ url_for('users.register') }}>Register!</a>
</div>
<div>
    <form action="" method="post">
        {{ form.csrf_token }}
        <div>
            {{ form.username.label(class="form-control-label green-text") }}
            {{ form.username(class="form-control form-control-md") }}

            {% if form.username.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in form.username.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div>
            {{ form.password.label(class="form-control-label") }}
            {{ form.password(class="form-control form-control-lg") }}
        </div>
        <div>
            {{ form.mfa_code.label(class="form-control-label green-text") }}
            {{ form.mfa_code(class="form-control form-control-md") }}

            {% if form.mfa_code.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in form.mfa_code.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div>
            {{ form.submit(class="btn btn-block btn-primary") }}
        </div>
    </form>
</div>
{% endblock %}

flask_app/templates/mfa_confirm_page.html
{% extends "base.html" %}
{% block content %}
<div>
    <h2>Multi-Factor Authentication Confirm Page</h2>
    <div class="alert alert-danger" role="alert">
        Please note this page CANNOT be accessed later.
    </div>
    <p>
        Everytime when you login our website, you need to use our Multi-Factor Authentication. Please use Google
        Authenticator to scan this QR code.
    </p>
    <img src="https://api.qrserver.com/v1/create-qr-code/?size=500x500&data={{ qrcode }}" alt="">
    <div>
        If you completed the steps above, <a href={{ url_for('users.login') }}>Log In!</a>
    </div>
</div>
{% endblock %}

flask_app/templates/post_detail.html
{% extends "base.html" %}
{% block content %}
<article class="content-section">
    <div>
        <h3 style="margin-bottom: 15px">{{ post.title }}</h3>
        <div class="d-flex justify-content-between align-items-center">
            <small class="text-muted">
                {% if current_user.id == post.author.id %}
                <a href={{ url_for('posts.edit_post', id=post.id) }}>
                    Edit
                </a>
                {% else %}
                <a href={{ url_for('main.user_detail', id=post.author.id) }}>
                    {{ post.author.username }}
                </a>
                {% endif %}
            </small>
            <small class="text-muted">
                {{ post.date.strftime('%b %d, %Y at %I:%M %p') }}
            </small>
        </div>
        <hr>
        <p>{{ post.content | markdown }}</p>
    </div>
</article>
<br>
<hr>
<br>
{% if current_user.is_authenticated %}

<h3>Comments <small>({{ comments | length }})</small></h3>
<br>
<div class="list-group">
    {% for comment in comments %}
    <div class="card mb-4 shadow-sm">
        <div class="card-body">
            {{ comment.content | markdown }}
            <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">
                    <a href={{ url_for('main.user_detail', id=comment.author.id) }}>
                        {{ comment.author.username }}
                    </a>
                </small>
                <small class="text-muted">
                    {{ comment.date.strftime('%b %d, %Y at %I:%M %p') }}
                </small>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<hr>
<a class="btn btn-primary btn-block" href="{{ url_for('posts.create_comment', id=post.id) }}">Create Comment</a>
{% else %}
<h3>
    To view or send comments, please login first
</h3>
{% endif %}

{% endblock %}

flask_app/templates/register.html
{% extends "base.html" %}
{% block content %}
<div>
    <h2>Registration</h2>
</div>
<div>
    If you are registered, just <a href={{ url_for('users.login') }}>Log In!</a>
</div>
<!-- Registration Form: -->
<div>
    <form action="" method="post">
        {{ form.csrf_token }}
        <div>
            {{ form.username.label(class="form-control-label green-text") }}
            {{ form.username(class="form-control form-control-md") }}

            {% if form.username.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in form.username.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div>
            {{ form.email.label(class="form-control-label green-text") }}
            {{ form.email(class="form-control form-control-md") }}

            {% if form.email.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in form.email.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div>
            {{ form.password.label(class="form-control-label") }}
            {{ form.password(class="form-control form-control-lg") }}

            {% if form.password.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in form.password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div>
            {{ form.confirm_pwd.label(class="form-control-label") }}
            {{ form.confirm_pwd(class="form-control form-control-lg") }}
        </div>
        <br>
        <div>
            {{ form.submit(class="btn btn-block btn-primary") }}
        </div>
    </form>
</div>

{% endblock %}

flask_app/templates/user_detail.html
{% extends "base.html" %}
{% block content %}
<div>
    <h2>{{ user.username }}</h2>
    <hr>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h3>All Snippets</h3>
            <div class="list-group">
                {% for post in posts %}
                <div class="card mb-4 shadow-sm" style="cursor: pointer;"
                    data-href="{{ url_for('posts.post_detail', id=post.id) }}"
                    onclick="location.href=this.getAttribute('data-href');">
                    <div class="card-body">
                        <p class="card-text">{{ post.title }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <small class="text-muted">
                                {{ post.author.username }}
                            </small>
                            <small class="text-muted">
                                {{ post.date.strftime('%b %d, %Y at %I:%M %p') }}
                            </small>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

        <div class="col-md-4">
            <h3>All Comments</h3>
            <div class="list-group">
                {% for comment in comments %}
                <div class="card mb-4 shadow-sm" style="cursor: pointer;"
                    data-href="{{ url_for('posts.post_detail', id=comment.post.id) }}"
                    onclick="location.href=this.getAttribute('data-href');">
                    <div class="card-body">
                        {{ comment.content | markdown }}
                        <div class="d-flex justify-content-between align-items-center">
                            <small class="text-muted">
                                <a href={{ url_for('main.user_detail', id=comment.author.id) }}>
                                    {{ comment.author.username }}
                                </a>
                            </small>
                            <small class="text-muted">
                                {{ comment.date.strftime('%b %d, %Y at %I:%M %p') }}
                            </small>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>

        </div>
    </div>
</div>
{% endblock %}